CREATE DATABASE BaseDeDatosDeContacto
USE BaseDeDatosDeContacto;
CREATE TABLE InfPersonal (
IDInfPers INT PRIMARY KEY,
Cedula INT NOT NULL,
Nombre NVARCHAR(50) NOT NULL,
FechaNacimiento DATE
);

CREATE TABLE Empleo (
IDEmpleo VARCHAR(10) PRIMARY KEY,
TrabajoActual VARCHAR(50),
TrabajoAnterior VARCHAR(50) NOT NULL
);
CREATE TABLE Domicilio (
IDDomicilio VARCHAR(10) PRIMARY KEY,
DireccionAnterior NVARCHAR(50) NOT NULL,
DireccionActual NVARCHAR(50)
);

CREATE TABLE Contacto (
IDContacto VARCHAR(10) PRIMARY KEY,
TelefonoConvencional VARCHAR(12) NOT NULL,
Email NVARCHAR(30) NOT NULL,
Celular NVARCHAR(15) NOT NULL
);

CREATE TABLE BienesInmuebles (
IDBienesInm VARCHAR(10) PRIMARY KEY,
Tipo VARCHAR(15) NOT NULL,
Direccion NVARCHAR(20) NOT NULL
);

CREATE TABLE BienesMuebles (
IDBienesMue VARCHAR(10) PRIMARY KEY,
Tipo VARCHAR(15) NOT NULL,
Placa NVARCHAR(10) NOT NULL,
);

CREATE TABLE HistorialMigratorio (
IDHistorialMigratorio VARCHAR(10) PRIMARY KEY,
UltimaEntrada NVARCHAR(15) NOT NULL,
UltimaSalida NVARCHAR(15) NOT NULL
);

CREATE TABLE Educacion (
IDEdu VARCHAR(10) PRIMARY KEY,
NivelDeEstudios VARCHAR(15) NOT NULL,
LugarDeObtencion NVARCHAR(20) NOT NULL
);
CREATE TABLE Amigos (
IDAmigos VARCHAR(10) PRIMARY KEY,
Amigos NVARCHAR(20) NOT NULL
);
CREATE TABLE Familiares (
IDFamiliares VARCHAR(10) PRIMARY KEY,
Familiares NVARCHAR(20) NOT NULL,
Parentezco VARCHAR(15) NOT NULL
);
CREATE TABLE NivelEstudios (
IDNivEst VARCHAR(10) PRIMARY KEY,
Tipo VARCHAR(15)
);
CREATE TABLE Genero (
IDGenero VARCHAR(10) PRIMARY KEY,
Tipo VARCHAR(10) NOT NULL
);
CREATE TABLE EstadoCivil (
IDEstadoCivil VARCHAR(10) PRIMARY KEY,
Tipo VARCHAR(10) NOT NULL
);
CREATE TABLE Relaciones (
IDInfPersonal INT FOREIGN KEY REFERENCES InfPersonal (IDInfPers),
IDEmpleo VARCHAR(10) FOREIGN KEY REFERENCES Empleo (IDEmpleo),
IDDomicilio VARCHAR(10) FOREIGN KEY REFERENCES Domicilio (IDDomicilio),
IDContacto VARCHAR(10) FOREIGN KEY REFERENCES Contacto (IDContacto),
IDBienesInm VARCHAR(10) FOREIGN KEY REFERENCES BienesInmuebles (IDBienesInm),
IDBienesMue VARCHAR(10) FOREIGN KEY REFERENCES BienesMuebles (IDBienesMue),
IDHistorialMigratorio VARCHAR(10) FOREIGN KEY REFERENCES HistorialMigratorio (IDHistorialMigratorio),
IDEdu VARCHAR(10) FOREIGN KEY REFERENCES Educacion (IDEdu),
IDAmigos VARCHAR(10) FOREIGN KEY REFERENCES Amigos (IDAmigos),
IDFamiliares VARCHAR(10) FOREIGN KEY REFERENCES Familiares (IDFamiliares),
IDNivEst VARCHAR(10) FOREIGN KEY REFERENCES NivelEstudios (IDNivEst),
IDGenero VARCHAR(10) FOREIGN KEY REFERENCES Genero (IDGenero),
IDEstadoCivil VARCHAR(10) FOREIGN KEY REFERENCES EstadoCivil (IDEstadoCivil),
);

SELECT * FROM Relaciones;